// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLamNAm3_Y7p4kR7PaHT9IfxbO_VZBvi4',
    appId: '1:384122754907:web:4e2129d9a1823fd4962c7e',
    messagingSenderId: '384122754907',
    projectId: 'order-tracker-b9fdc',
    authDomain: 'order-tracker-b9fdc.firebaseapp.com',
    storageBucket: 'order-tracker-b9fdc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBbCbb9Zcrrz6P95WZrke1z8t2xScmLOE',
    appId: '1:384122754907:android:c4301b79d2fd254d962c7e',
    messagingSenderId: '384122754907',
    projectId: 'order-tracker-b9fdc',
    storageBucket: 'order-tracker-b9fdc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMFPJoZHoaLTSTRu-a7Itldd87izwMMn4',
    appId: '1:384122754907:ios:c90e10d196273b64962c7e',
    messagingSenderId: '384122754907',
    projectId: 'order-tracker-b9fdc',
    storageBucket: 'order-tracker-b9fdc.appspot.com',
    iosBundleId: 'jonorams.org.inventoryTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLamNAm3_Y7p4kR7PaHT9IfxbO_VZBvi4',
    appId: '1:384122754907:web:559d169612b84720962c7e',
    messagingSenderId: '384122754907',
    projectId: 'order-tracker-b9fdc',
    authDomain: 'order-tracker-b9fdc.firebaseapp.com',
    storageBucket: 'order-tracker-b9fdc.appspot.com',
  );
}
